FROM shawnyan/docker:centos7.3.1611
MAINTAINER Shawn Yan https://github.com/shawn0915/docker-study

RUN yum install -y vim*
RUN echo 'centos7.3_base 2017-10-01' > /root/Readme.md

LABEL name="CentOS 7.3" \
    build-date="20171001"

CMD ["/bin/bash"]